### ISSUE TITLE
Do we need max frame-average luminance as well as max?

### ISSUE THREAD

**Issue by halliwell-g** [WICG/media-capabilities#16]
HDR displays typically can't display all their pixels at max luminance (heat, power issues) and will auto-dim if you send such a signal.  Typical HDR metadata includes max frame-average luminance separately from max (defined to be single-pixel).

**Comment by mwatson2** [comment]
The current definition of max (or min) screen luminance does not specify the screen area (single pixel or otherwise). On LCD displays the max luminance can typically only be achieved with some non-trivial amount of the screen area illuminated, because they would typically not crank a backlight all the way up for a single pixel due to the effect on the rest of the backlit area.

But, stepping back from the definitions, what is the intended use of these metrics ? We should understand that better in order to decide how they should be defined.

I think there will be many cases where these values are not available anyway. Even if one was going to use these metrics to determine whether it was "worth" sending HDR content vs SDR - in terms of whether this would offer an improvement in visual experience - one would need to know ambient light conditions and also whether and how user brightness controls affect the rendering. And then the judgement remains a very subjective one.

I think the decision on whether to use HDR or SDR content will likely be based simply on whether the renderer + display has the _capability_ to interpret and render an HDR signal. As with other aspects of this specification, this may differ for video vs graphics content.

**Comment by mounirlamouri** [comment]
@halliwell-g I've added the clarifications you asked for in the specification.

@mwatson2 wouldn't luminance help figure out if a screen is HDR capable? or would you consider a screen able to display let say `p3` a good enough signal for HDR? My understanding is that for desktop platforms, HDR requires more information than just the color gamut and SDR screens are able to display `p3` for exampe (or close enough to it).

**Comment by mwatson2** [comment]
@mounirlamouri You haven't addressed the issues I raised in my comment, you just committed a change without any chance for review.

I would think these attributes should be removed, unless we have some idea of how they are going to be made reliably available and how they are going to be used.

Yes, HDR is more than just wider color gamut, you also need to support a transfer function such as PQ or HLG. But all we can reliably indicate as capabilities is the capability to **render encoded data** using a given color space / transfer function. The actual capability of the display panel may be different from that or unknown (HDMI case). No panel supports the full 2020 gamut, for example, or the full PQ luminance range.
