### ISSUE TITLE
Capabilities can change based on the environment. Spec should address this...

### ISSUE THREAD

**Issue by miu-at-google** [WICG/media-capabilities#26]
After reviewing the current spec, I'm concerned that it assumes the capabilities of the system/platform are never changing. Or, at the least, clients of the API have to know to make further calls to get updated capabilities information; but how would they know *if* and *when* to do this? (It also seems that Video/AudioConfiguration assumes content streams will never change their size, rates, etc.; but that's often not the case.)

For example, what if the decoding capabilities of the platform change because, say, a HW decoder is present, but in-use by another app? Or, maybe a laptop was plugged in at one point, but now it is not? Or, maybe an external monitor was plugged in, but now is not? How would the client of this API ever be aware and adjust? This can be critical to the user experience when considering things like the resource requirements to play back 4K video, or codecs that have resource-hungry software implementations (but are preferred when a HW decoder is available).

To be even more specific (impact on my own product feature): I am currently working on a new Chrome browser media feature which is about to launch: Media Remoting. This will allow the content bitstream of HTML media elements to be redirected to a remote display device (e.g., a Chromecast attached to a TV). The user turns this on by starting Chrome Tab Mirroring to a Google Cast Receiver device, and then Chrome will automatically detect cases where content remoting is supported. W.R.T. media capabilities, this means a page could query for capabilities before the user starts Tab Mirroring; and get the capabilites for the normal local browser playback case. Later, once the user starts Tab Mirroring, it's possible an older Chromecast is being used that does not support the same set of codecs. However, for quality reasons, it would be highly desirable if the page were notified of the new set of capabilities so that content remoting could activate.

**Comment by chcunningham** [comment]
Thanks for filing! Haven't had a chance to discuss with Mounir yet, so speaking just for me...

At a high level, we'd like to separate real-time experience management (GPU/CPU contention, network reliability, etc) from answering the question of what your platform is ideally capable of. But this is different from "you had a HDR display plugged in, and now you don't" (which we plan to signal via [event](https://wicg.github.io/media-capabilities/#dom-screen-onchange)). I think the Media Remoting use case is a closer to the second category. 

The weird thing about Media Remoting is the system's internal capabilities have not changed. If you start tab casting perhaps thats a strong enough signal of user intent that we should start view your capabilities as the intersection of you + the remote endpoint (I'm not sure, just thinking out loud)? If we go this route we could do something simple like throw an onchange event into MediaCapabilities and just let folks re-query(). 

Alternatively, we might do something more specific to remoting. I'm not familiar with the API, but I imagine there is some event raised when remoting is initiated? This could be a signal for the app to query the remote end point's capabilities (perhaps the same API, but hanging off some remoting object rather than navigator) and decide for itself how to prioritize local/remote capabilities. 

WDYT?

If we go the intersection route, there will be cases where the system capabilities are degreed by a less capable remote. Say the system is happy to play 4k 60fps, but then the user casts the tab and finds the locally played video is now 1070p 30fps due to an older cast device. Not saying this is a non-starter, just something to consider.

**Comment by kentuckyfriedtakahe** [comment]
Much of this API depends upon the browser being able to predict the future. If the prediction turns out to be wrong then we fall back to counting dropped frames. For this reason I recommend removing AudioConfiguration and VideoConfiguration from the spec and instead focus on improving the dynamic cases.

We currently use dropped frames for the dynamic responsive case. The browser should have an explicit signal that it is not able to continue playback. For the dynamic predictive case, we need to implement an API that queries the browser relative to the current playback. For example query if the browser thinks it can play back at 1.5 times the current bitrate.

**Comment by chcunningham** [comment]
@mounirlamouri thoughts on my comment above?

@kentuckyfriedtakahe 
I agree that dynamic capabilities are important, but this API does not currently aim to solve that problem. We will not attempt to predict the future. The claims of support, smoothness and power efficiency are based on the decoders available (and whether they are hardware accelerated) and the system specs. We may refine the claims by assessing past claims against past performance, but this isn't the same as dynamic response. 

Dynamic / realtime experience reporting is currently the ambition of [MediaPlaybackQuality](https://github.com/WICG/media-playback-quality). @mounirlamouri has taken ownership for that spec (and I'm also pretty interested). Feel free to file ideas and bugs there.

**Comment by mounirlamouri** [comment]
I think the media remoting use case doesn't work very well. It would reflect the media remoting to the page, while I would assume the page isn't aware it is being played remotely which can create privacy issues. In general, I think that we don't want to handle change events for the capabilities: they are meant to be absolute and the spec for example mentions that current system usage for example should be ignored. The case where the hardware capabilities are changing seems too narrow to justify an API change. I wouldn't be able to name any real life situation where this could happen.

Regarding media remoting, shouldn't the solution to ask the remote device about the capabilities and decide whether to toggle media remoting based on this? Maybe this should be a good use case for the [Open Screen Protocol](https://github.com/webscreens/openscreenprotocol)?

**Comment by mounirlamouri** [comment]
I'm going to close this as there is no obvious next steps a part from #43.
