### ISSUE TITLE
HDCP Policy Check: which display is represented when there are multiple displays?

### ISSUE THREAD

**Issue by PauKerr** [WICG/media-capabilities#53]
Which display is represented by the answer when there are multiple displays? If the MediaKeys object is associated with an HTMLMediaElement perhaps it should be the display with the "lowest" HDCP capability of all displays showing any portion of the media element. Is the internal display treated as the primary and target of this check call?

Can you detail the steps used to determine how the query is resolved?

**Comment by xhwang-chromium** [comment]
The CDM should use the same mechanism to decide the key status the same as it would use to determine the key status for real decryption keys. As for how CDM does this, I feel it should be CDM specific. Your suggestion (lowest HDCP capability of all displays showing part of the media) is definitely one possibility. But the CDM doesn't always have the access to all the information needed to do that, e.g. due to sandboxing, or OS system API limitations. So another possibility is that the CDM will just use the lowest HDCP capability of all displays, regardless on which display(s) the video is shown.

**Comment by mounirlamouri** [comment]
I think it would be useful to have a note about this in the spec. Mentioning that there are multiple strategies and maybe point to a couple (the ones you mentioned above)? @xhwang-chromium WDYT?

**Comment by xhwang-chromium** [comment]
A NOTE on this sgtm.

**Comment by chcunningham** [comment]
Moved to hdcp-detection's tracker.
