### ISSUE TITLE
Make policy check similar to HLS and UWP

### ISSUE THREAD

**Issue by beaufortfrancois** [WICG/media-capabilities#63]
- HLS uses `HDCP-LEVEL=NONE`, `HDCP-LEVEL=TYPE-0`, `HDCP-LEVEL=TYPE-1`  - [(source)](https://developer.apple.com/library/content/documentation/General/Reference/HLSAuthoringSpec/appendix.html)
- Universal Windows Platform (UWP) uses `COPP_HDCP_Level0`, `COPP_HDCP_Level1` - [(source)](https://msdn.microsoft.com/en-us/library/windows/desktop/dd387938%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396)

How about making the Media Capabilities HDCP policy check similar to make web developers life easier?

```
dictionary MediaKeysPolicy {
  DOMString minHdcpLevel = ""; // "Type 1" or "Type 0"
};
```

Example:
```js
const status = await video.mediaKeys.getStatusForPolicy({ minHdcpLevel: 'Type 1' });
if (status == 'usable') {
  // Pre-fetch HD content.
} else {  // such as 'output-restricted' or 'output-downscaled'
  // Pre-fetch SD content.
}
```

**Comment by mounirlamouri** [comment]
ping @xhwang-chromium @mwatson2

**Comment by xhwang-chromium** [comment]
Are those strings standardized? If not, I am not sure whether we should try to be consistent with them. 

Also, in the HDCP spec, these number are "revisions", e.g. "revision 1.4", which is referred to as "HDCP 1.4".

> This specification describes the High-bandwidth Digital Content Protection (HDCP) system,
> Revision 1.40, referred to as HDCP 1.4. HDCP 1.4 is a revision update to HDCP, Revision
> 1.30 and its errata, referred to collectively as HDCP 1.3.

It's not a type, nor a level. I agree the current string we pick is not perfect (we debated on whether it should be a string or an enum), but is still better the alternatives you listed IMHO.

**Comment by PauKerr** [comment]
In HDCP usage, the Type parameter is an attribute of the content stream: you can have a Type 0 or a Type 1 content stream. The requirements associated with a Type 1 stream are dependent on the HDCP version. For example, an HDCP 2.0 device may not transmit Type 1 content to an HDCP 1.x receiver while an HDCP 2.2 device may not transmit Type 1 content to either an HDPC 1.x or HDCP 2.0 devices. The version of HDCP supported by the display path is needed in order to determine whether it is acceptable stream Type 0 or Type 1 content.

**Comment by xhwang-chromium** [comment]
PauKerr: Thanks for the explanation. Is this "Type 0" and "Type 1" content stream defined anywhere? Or is it specific to some content providers?

**Comment by PauKerr** [comment]
From the HDCP spec:

https://www.digital-cp.com/sites/default/files/specifications/HDCP%20Interface%20Independent%20Adaptation%20Specification%20Rev2_2_FINAL.pdf

The field is defined in Table 4.19.

**Comment by beaufortfrancois** [comment]
For future reference, here's an extract of the HDCP spec below:

> 
> _streamCtr_ assigned to an elementary stream is concatenated with its corresponding ContentStreamlD value and its assigned Type value. All values are in big-endian order. 
> 
> _k_ is the number of elementary streams that are being transmitted by the HDCP Transmitter to the attached HDCP Repeater during the HDCP Session. 
> 
> Parameter | No. of Bytes | Description |
> -----------------|-------------|----|
> ContentStreamID | 2 | Content Stream Identification This parameter must be assigned the PID value as follows. <ul><li>ContentStreamID[15:13] = 0</li><li> ContentStreamID[12:0] = PID</li><lu> |
> Type | 1 | <ul><li>0x00 : Type 0 Content Streams. May be transmitted by the HDCP Repeater to all HDCP Devices. </li><li>0x01 : Type 1 Content Streams. Must not be transmitted by the HDCP Repeater to HDCP 1.x-compliant Devices and HDCP 2.0-compliant Repeaters </li><li> 0x02 — OxFF : Reserved for future use only. Content Streams with reserved Type values must be treated similar to Type 1 Content Streams i.e. must not be transmitted by the HDCP Repeater to HDCP 1.x-compliant Devices and HDCP 2.0-compliant Repeaters </li></ul> |
> 
> _Table 4.19. RepeaterAuth_Stream_Manage Parameters_

**Comment by PauKerr** [comment]
Also important to note, this same section in the HDCP 2.0 and 2.1
specification states that Type 1 Content Streams cannot be transmitted to
an HDCP 1.x-compliant device. What this means is that asking a display
subsystem whether it is able to transmit a Type 1 stream to a display will
mean two different levels of security based on whether the display
subsystem is a 2.2 or pre-2.2 compliant transmitter. If I have content that
I wish to treat as Type 1 content, and seek to avoid the possibility of the
stream being compromised by a cracked 2.1 receiver, I need to know if the
browser will apply the HDCP 2.2 rule.

For the purposes of this interface, "Type 1" should map to the HDCP 2.2
rule-set. Alternately, let minHdcpLevel be the HDCP spec number for finer
level queries: HDCP_2.1, HDCP_2.2, etc.



On Tue, Nov 28, 2017 at 1:52 AM, François Beaufort <notifications@github.com

**Comment by xhwang-chromium** [comment]
Sorry for belated reply. I finally got time to read this "Type" section.

It seems to me Type1 and Type2 are the properties of the streams, not the display connection itself. Also, as pointed our by PauKerr, only using Type 1 and Type 2 hides a lot of useful information, e.g. cannot differentiate b/w HDCP 2.2 and pre-HDCP 2.2 versions.

Also, some policy may require a specific HDCP version, so using stream type in the "policy check" API would cause a gap between this API and the real policy to enforce.

Overall, I feel since this is HDCP policy check, we should stick with the HDCP version, instead of using a  stream type which doesn't map well into HDCP versions.

**Comment by beaufortfrancois** [comment]
From what I understand "Type 0" is pre-HDCP 2.2 while "Type 1" is HDCP 2.2 for now.

Which kind of policy do you think might require a specific version of HDCP? I can't find one.

**Comment by chcunningham** [comment]
> From what I understand "Type 0" is pre-HDCP 2.2 while "Type 1" is HDCP 2.2 for now.

Type 1 is also described in the 2.1 spec. 
https://www.digital-cp.com/sites/default/files/HDCP%20Interface%20Independent%20Adaptation%20Specification%20Rev2_1.pdf

> Which kind of policy do you think might require a specific version of HDCP?

A hypothetical Netflix policy (i.e. not to be found in a spec). The point Paul is making is that, because 2.1 is cracked, and because Type 1 could refer to either 2.1 or 2.2, he either wants us to expose the exact HDCP version, or only say we can do Type 1 when version == 2.2.

This + xhwang's points are a good reason to have the API take Version instead of Type.

I think we're pretty close to consensus, and the HDCP spec has actually [moved here](https://github.com/WICG/hdcp-detection/) (just getting started). If anyone here wants to follow up on this discussion, please file a bug in that repo.
